# Generated by Django 6.0 on 2026-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_settlement_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CASH', 'Cash')], max_length=20, null=True),
        ),
    ]
