# Generated by Django 6.0 on 2026-01-14 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_id_alter_groupinvite_id'),
        ('payments', '0003_alter_paymenthistory_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CASH', 'Cash')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
