# Generated by Django 6.0 on 2025-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_created_by_expense_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('custom', 'Custom')], default='equal', max_length=20),
        ),
    ]
