# Generated by Django 6.0 on 2025-12-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_expense_split_between_alter_expensesplit_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
