# Generated by Django 6.0 on 2026-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
