# Generated by Django 6.0 on 2026-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_id_alter_groupinvite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
